### ISSUE TITLE
 An error occurred when starting the program

### ISSUE THREAD

**Issue by piggycatc** [fougue/mayo#177] opened 2023-02-22 00:20 UTC
When I run it for the first time and open the file, it works fine, but when I run the program again later, the program closes.
It appears to be due to another language on the path.
If there are other languages ​​on the path, the program will exit without running.

**Comment by HuguesDelorme** [comment] 2023-02-22 08:53
Can you give an example of a file path that causes the crash ?

**Comment by akjay** [comment] 2023-02-22 14:37
If the path has chinese characters，it will crash.

**Comment by HuguesDelorme** [comment] 2023-02-22 14:52
@akjay
Can't reproduce it with develop branch:
![image](https://user-images.githubusercontent.com/939132/220658731-efc70d8b-17e2-4370-8f00-d906dcc92d82.png)

Are you using v0.6.0 binaries provided in the Releases page?

**Comment by akjay** [comment] 2023-02-23 02:51
> @akjay
> Can't reproduce it with develop branch:
> ![image](https://user-images.githubusercontent.com/939132/220658731-efc70d8b-17e2-4370-8f00-d906dcc92d82.png)
> 
> Are you using v0.6.0 binaries provided in the Releases page?

I use 0.6.0.1012.
After the lastOpenFolder record this file path，the you can try open Mayo.exe and close it with nothing other operation，maybe two or three times it will crash.Then need go to regedit to clean lastOpenFolder setting for recover.

**Comment by piggycatc** [comment] 2023-02-23 04:14
Just deleting the 'lastOpenFolder' registry will make it run normally again.

And the list of recently opened files is still visible.

**Comment by HuguesDelorme** [comment] 2023-03-13 15:58
@piggycatc and @akjay 
Just tried the v0.6.0.1012 version within a virtualized Win7 x64 machine:
![image](https://user-images.githubusercontent.com/939132/224756904-ca7dd6dd-5778-4b4a-a278-0356ca6a869c.png)

Still can't reproduce the problem!
Maybe related to the locale of your systems?

**Comment by piggycatc** [comment] 2023-03-14 05:07
It's not a filename problem, it's a path problem. If there are other characters on the path, the program will stop. Or you can check it by running it and turning it off three times.

windows10  x64, i7 - 16G - Nvidia gtx1050
windows11 x64 i5 - 16G - Nvidia rtx3050ti

**Comment by HuguesDelorme** [comment] 2023-03-14 07:49
@piggycatc and @akjay
Here is what I tried without any problem:
![image](https://user-images.githubusercontent.com/939132/224930681-f2f36a52-64dd-46b1-9bbb-00f45c3d28b9.png)

The full path of the file is `C:\Tests\热情\file_一号文件.stp`
Should this path cause a crash on your machine?

**Comment by HuguesDelorme** [comment] 2023-03-29 08:45
@piggycatc and @akjay 
Please let me know if the issue still remains with new 0.7.0 version
Thanks!

**Comment by piggycatc** [comment] 2023-03-30 04:43
> 
Tested with version 0.7.0
When I open the file for the first time, it runs normally.


The text on the path is normal Korean.

![ifdocumentskor](https://user-images.githubusercontent.com/93959702/228730258-1d6457f4-80bc-48ae-b6e4-bd6b0634938a.PNG)


It is an Lastopen folder's Path in the registry

![ifdocuments](https://user-images.githubusercontent.com/93959702/228730607-acf3c5db-71fb-4289-bbac-22ed03a20e7f.PNG)

third run and then program stopped 

![noanswer](https://user-images.githubusercontent.com/93959702/228730773-90913006-69cc-4048-aa26-4a5993210313.PNG)


text broken in the registry path
![ifchanged](https://user-images.githubusercontent.com/93959702/228731124-956191be-c7b9-434e-87e0-9739066cc536.PNG)

**Comment by HuguesDelorme** [comment] 2023-03-30 08:25
Maybe I found the explanation:
https://engineertips.wordpress.com/2021/10/03/windows-path-separators/

**Comment by HuguesDelorme** [comment] 2023-06-01 10:38
@piggycatc @akjay 
Can one or both of you please join here a crashdump file?
Make sure crashdump generation is ON with your system: https://learn.microsoft.com/en-us/windows/win32/wer/collecting-user-mode-dumps

Thanks for your feedback!

**Comment by akjay** [comment] 2023-06-13 11:48
> @piggycatc @akjay 
> Can one or both of you please join here a crashdump file?
> Make sure crashdump generation is ON with your system: https://learn.microsoft.com/en-us/windows/win32/wer/collecting-user-mode-dumps
> 
> Thanks for your feedback!

ok,will try later.

**Comment by kantoku-code** [comment] 2023-08-14 14:19
@HuguesDelorme -San.

Thanks for the great software.

I am Japanese, but similarly, if the file path contains 2 byte characters (multibyte characters), it crashes and does not start when restarting.
This is ver 0.7.0.

**Comment by HuguesDelorme** [comment] 2023-11-02 14:29
@kantoku-code 
Can you checkout `develop` branch and check if the crash still happen? It might be fixed as as side effect of #219

**Comment by kantoku-code** [comment] 2023-11-02 15:14
@HuguesDelorme -San.

We decided to respond by creating a VBScript to start Mayo after deleting the registry.
[MayoStarter.zip](https://github.com/fougue/mayo/files/13241387/MayoStarter.zip)

**Comment by HuguesDelorme** [comment] 2023-11-14 15:39
Duplicate of #219

**Closed by HuguesDelorme** 2023-11-14 15:39 UTC
Labels: bug, crash

**Comment by HuguesDelorme** [comment] 2023-12-20 17:38
@kantoku-code @akjay @piggycatc 
Can one of you please test if this crash still happen with latest version([v0.8.0](https://github.com/fougue/mayo/releases/tag/v0.8.0))?

**Comment by kantoku-code** [comment] 2023-12-21 01:28
@HuguesDelorme  -San.

Sorry for the delay in confirmation.
For Japanese, this issue has been resolved in v0.8.0.
Thanks.
