### ISSUE TITLE
"File transfer problem" Error when debug mode,but release has no problem

### ISSUE THREAD

**Issue by dansirming** [fougue/mayo#66] opened 2021-05-04 08:50 UTC
dear expert：
     recently I encounter a  problem! that is : some step files are opened by mayo under debug mode,pop up "File transfer problem"
error prompt, but has no problem under release mode, I has positioned "src/io_occ/io_occ_caf.cpp/cafGenericReadTransfer/reader.Transfer",
I am so sure that the step file is correct!  the network is so bad, so step file can not upload ! can you help me ? thank you!

[888.zip](https://github.com/fougue/mayo/files/6419940/888.zip)

**Comment by dansirming** [comment] 2021-05-04 08:54
888.zip is my step file ,you can use it test,thank you !

**Comment by dansirming** [comment] 2021-05-04 08:56
my environment ：Qt  5.14.1,  OpenCASCADE-7.5.0   Or    OpenCASCADE-7.3.0

**Comment by HuguesDelorme** [comment] 2021-05-04 08:58
Hello @dansirming 
Are you using latest version of `develop` branch ?
I think the issue you reported is fixed with #65

**Comment by HuguesDelorme** [comment] 2021-05-04 09:32
Loaded `888.STEP` with Mayo built from `develop` branch :
![image](https://user-images.githubusercontent.com/939132/116985194-6dc70f00-accc-11eb-8daf-19bdfc68c976.png)

**Comment by dansirming** [comment] 2021-05-04 09:40
I download "mayo-717ef14de682ecc2f145057750d3099d3e19031",but still pop up&nbsp;"File transfer problem", can you tell me you use which version ? thank you very much !





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fougue/mayo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月4日(星期二) 下午5:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fougue/mayo] "File transfer problem" Error when debug mode,but release has no problem (#66)





 
Loaded 888.STEP with Mayo built from develop branch :

**Comment by dansirming** [comment] 2021-05-04 09:41
I download "mayo-717ef14de682ecc2f145057750d3099d3e19031",but still pop up "File transfer problem" under debug mode, can you tell me you use which version ? thank you very mu
![2021-05-04_173656](https://user-images.githubusercontent.com/38598451/116986131-ff9c3f80-acff-11eb-9cef-e08ec6e0f1f2.png)
ch !

**Comment by dansirming** [comment] 2021-05-04 09:44
I download "mayo-3717ef14de682ecc2f145057750d3099d3e19031",but still pop up "File transfer problem" under debug mode,&nbsp;&nbsp;but has no problem under release mode, can you tell me you use which version ? thank you very much!
![2021-05-04_173656](https://user-images.githubusercontent.com/38598451/116986131-ff9c3f80-acff-11eb-9cef-e08ec6e0f1f2.png)
ch !






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fougue/mayo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月4日(星期二) 下午5:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fougue/mayo] "File transfer problem" Error when debug mode,but release has no problem (#66)





 
Loaded 888.STEP with Mayo built from develop branch :

**Comment by HuguesDelorme** [comment] 2021-05-04 09:44
That seems latest version from the commit id you give.
Seems like you build Mayo with OpenCascade 7.3 ?
Do you have the same issue with OpenCascade 7.5 ? This is the version I'm using(from OpenCascade's Download center)

**Comment by dansirming** [comment] 2021-05-04 09:47
I Has tried many times!  both OpenCascade 7.3  and OpenCascade 7.5 all pop up  "File transfer problem" under debug mode

**Comment by dansirming** [comment] 2021-05-04 09:54
> from OpenCascade's Download center

I download from OpenCascade's Download center and will try soon! thank you very much

**Comment by HuguesDelorme** [comment] 2021-05-04 09:56
OpenCascade Download Center ;
https://dev.opencascade.org/release

**Comment by dansirming** [comment] 2021-05-04 10:11
I Has tried just now, from OpenCascade Download Center https://dev.opencascade.org/release,pop up "File transfer problem" under debug mode 

![2021-05-04_180829](https://user-images.githubusercontent.com/38598451/116989263-1e9cd080-ad04-11eb-83f6-b8f851f38f01.png)

**Comment by dansirming** [comment] 2021-05-04 10:14
reader.Transfer return flase undet debug mode!
![2021-05-04_181237](https://user-images.githubusercontent.com/38598451/116989569-80f5d100-ad04-11eb-8960-803e4b580398.png)

**Comment by dansirming** [comment] 2021-05-04 10:15
I Has tried just now, from OpenCascade Download Center&nbsp;https://dev.opencascade.org/release,pop&nbsp;up "File transfer problem" under debug mode ,why has no problem under release mode?






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fougue/mayo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月4日(星期二) 下午5:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fougue/mayo] "File transfer problem" Error when debug mode,but release has no problem (#66)





 
OpenCascade Download Center ;
 https://dev.opencascade.org/release

**Comment by dansirming** [comment] 2021-05-04 10:16
reader.Transfer return flase under debug mode!







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fougue/mayo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月4日(星期二) 下午5:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fougue/mayo] "File transfer problem" Error when debug mode,but release has no problem (#66)





 
OpenCascade Download Center ;
 https://dev.opencascade.org/release

**Comment by dansirming** [comment] 2021-05-04 10:18
thank you for help me!&nbsp;Wish&nbsp;you&nbsp;all&nbsp;happiness,&nbsp;health&nbsp;and&nbsp;prosperity！！！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fougue/mayo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月4日(星期二) 下午5:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fougue/mayo] "File transfer problem" Error when debug mode,but release has no problem (#66)





 
OpenCascade Download Center ;
 https://dev.opencascade.org/release

**Comment by HuguesDelorme** [comment] 2021-05-04 10:37
Problem still exist with "official" OpenCascade binaries ?
What happens if you try with Mayo v0.3 installer(see Releases [page](https://github.com/fougue/mayo/releases/tag/v0.3.0)) ?
Sorry that's not easy to help, as I didn't reproduce your issue on my side.

**Comment by dansirming** [comment] 2021-05-04 11:07
with "official" OpenCascade binaries has no problem&nbsp;，because binaries is compiled out under release mode by source code, but&nbsp; with "official" OpenCascade "Mayo"&nbsp; source code(as below picture) compiled out a binaries that&nbsp; under debug mode ,the&nbsp;&nbsp;issue&nbsp; will reproduce&nbsp;! you can download&nbsp; "official" OpenCascade Mayo source code(as below picture)&nbsp; and try to use&nbsp;888.zip step file&nbsp;under&nbsp;debug mode&nbsp;,then you can reproduce this issue，bless you good luck！





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fougue/mayo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月4日(星期二) 晚上6:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fougue/mayo] "File transfer problem" Error when debug mode,but release has no problem (#66)





 
Problem still exist with "official" OpenCascade binaries ?
 What happens if you try with Mayo v0.3 installer(see Releases page) ?
 Sorry that's not easy to help, as I didn't reproduce your issue on my side.

**Comment by HuguesDelorme** [comment] 2021-05-04 13:40
I tried with OpenCascade 7.5.0 built from source code in debug configuration:
3RDPARTY_DIR=<rootdir_of_official_occ7.5>
BUILD_USE_PCH=ON
BUILD_WITH_DEBUG=ON
BUILD_LIBRARY_TYPE=Shared
BUILD_YACCLEX=OFF
USE_FFMPEG=OFF
USE_FREEIMAGE=ON
USE_GLES2=OFF
USE_OPENVR=OFF
USE_RAPIDJSON=ON
USE_TBB=ON
USE_VTK=OFF
...

I can open file `888.STEP` without problems.
Can you step into the call `reader.Transfer()` that return false ? You should see what's wrong there

**Comment by dansirming** [comment] 2021-05-05 02:30
“reader.Transfer()”&nbsp; in the lib， I can't step into it！it just return false。&nbsp;
I do mayo project by Visual studio 2017 use Qt Vs Toos&nbsp;plug-in(Qt core is 5.14.1),&nbsp;
now I send my mayo project&nbsp; to you,can you help me ? may be you can reproduce my issue on your side.thank you very much







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fougue/mayo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月4日(星期二) 晚上9:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fougue/mayo] "File transfer problem" Error when debug mode,but release has no problem (#66)





 
I tried with OpenCascade 7.5.0 built from source code in debug configuration:
 3RDPARTY_DIR=<rootdir_of_official_occ7.5&gt;
 BUILD_USE_PCH=ON
 BUILD_WITH_DEBUG=ON
 BUILD_LIBRARY_TYPE=Shared
 BUILD_YACCLEX=OFF
 USE_FFMPEG=OFF
 USE_FREEIMAGE=ON
 USE_GLES2=OFF
 USE_OPENVR=OFF
 USE_RAPIDJSON=ON
 USE_TBB=ON
 USE_VTK=OFF
 ...
 
I can open file 888.STEP without problems.
 Can you step into the call reader.Transfer() that return false ? You should see what's wrong there

**Comment by dansirming** [comment] 2021-05-10 07:38
dear expert:
&nbsp; &nbsp; &nbsp;today , I&nbsp; extract code from mayo project into myself project to&nbsp;satisfied my need , the&nbsp; problems which I encountered last week has not&nbsp;appeared， I guess that some configs Which I maked are not correct before&nbsp;. thank you very much!






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fougue/mayo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月4日(星期二) 晚上9:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fougue/mayo] "File transfer problem" Error when debug mode,but release has no problem (#66)





 
I tried with OpenCascade 7.5.0 built from source code in debug configuration:
 3RDPARTY_DIR=<rootdir_of_official_occ7.5&gt;
 BUILD_USE_PCH=ON
 BUILD_WITH_DEBUG=ON
 BUILD_LIBRARY_TYPE=Shared
 BUILD_YACCLEX=OFF
 USE_FFMPEG=OFF
 USE_FREEIMAGE=ON
 USE_GLES2=OFF
 USE_OPENVR=OFF
 USE_RAPIDJSON=ON
 USE_TBB=ON
 USE_VTK=OFF
 ...
 
I can open file 888.STEP without problems.
 Can you step into the call reader.Transfer() that return false ? You should see what's wrong there

**Comment by arthurx70** [comment] 2021-05-11 14:30
@dansirming,hello,can U tell me how to fix the problem, importing step file occur with transfer problem. did U compiled on win7 os? what configs U have changed?

**Comment by dansirming** [comment] 2021-05-16 09:16
dear expert:
&nbsp; &nbsp; &nbsp;last week so busy that I has no time to send mail to you. so sorry ！
&nbsp; &nbsp;&nbsp;last week&nbsp;&nbsp;I&nbsp; extracted code from mayo project into myself project to satisfied my need , the&nbsp; problems which I encountered last week has not appeared。the max&nbsp;changes as follow：


//&nbsp; &nbsp; -----------------------io_occ_step.cpp--------------------------
bool OccStepReader::readFile(const FilePath&amp; filepath, TaskProgress* progress)
{
&nbsp; &nbsp; MayoIO_CafGlobalScopedLock(cafLock);


	// 以下两句代码不要，否则debug模式下，有的文件打开会报错，release版则不会
&nbsp; &nbsp;&nbsp;OccStaticVariablesRollback rollback;
&nbsp; &nbsp; //this-&gt;changeStaticVariables(&amp;rollback);
&nbsp; &nbsp; return Private::cafReadFile(m_reader, filepath, progress);
}


//&nbsp; &nbsp; -----------------------io_occ_step.cpp--------------------------
bool OccStepReader::transfer(DocumentPtr doc, TaskProgress* progress)
{
&nbsp; &nbsp; MayoIO_CafGlobalScopedLock(cafLock);


	// 以下两句代码不要，否则debug模式下，有的文件打开会报错，release版则不会
&nbsp; &nbsp;OccStaticVariablesRollback rollback;
&nbsp; &nbsp;// this-&gt;changeStaticVariables(&amp;rollback);
&nbsp; &nbsp; return Private::cafTransfer(m_reader, doc, progress);
}



// --------------- my main widget class，&nbsp; &nbsp;super3DShowWnd.cpp
	super3DShowWnd::super3DShowWnd(GuiApplication* pGuiApp, QWidget *parent)
		: QWidget(parent), m_guiApp(pGuiApp)
	{
		ui.setupUi(this);


		this-&gt;setWindowFlags(Qt::CustomizeWindowHint | Qt::FramelessWindowHint);
		setAttribute(Qt::WA_AcceptTouchEvents);


		app-&gt;settings()-&gt;resetAll();
		app-&gt;settings()-&gt;load();
		
	}



I&nbsp;canceled the red codes in the “io_occ_step.cpp” and&nbsp; remove&nbsp; "settings()-&gt;load()"&nbsp; to the my main widget class ,&nbsp;&nbsp;the&nbsp; problems&nbsp;&nbsp;has not appeared&nbsp;! I tried to do that in mayo project,&nbsp;the&nbsp; problems&nbsp;&nbsp;has&nbsp; still&nbsp; appeared!
my&nbsp;environment as follow:


vs 2017、Qt 5.14.1、qt-vsaddin-msvc2017-2.4.1-rev.12.vsix，OpenCASCADE-7.5.0-vc14-64&nbsp; &nbsp;Or&nbsp; OpenCASCADE-7.3.0-vc14-64


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fougue/mayo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月11日(星期二) 晚上10:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fougue/mayo] "File transfer problem" Error when debug mode,but release has no problem (#66)





 
@dansirming,hello,can U tell me how to fix the problem, importing step file occur with transfer problem. did U compiled on win7 os? what configs U have changed?

**Comment by HuguesDelorme** [comment] 2021-05-17 08:51
@dansirming
One easy thing that's worth trying : edit settings in Mayo (menu Tools->Options) and restore default values for the "Import/STEP" section
![image](https://user-images.githubusercontent.com/939132/118461224-bd123400-b6fd-11eb-8ae9-e57f8e8e2f08.png)

**Comment by dansirming** [comment] 2021-05-21 10:17
I tried, but all the same!!!,the&nbsp;problem&nbsp;still&nbsp;&nbsp;appear！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fougue/mayo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月17日(星期一) 下午4:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fougue/mayo] "File transfer problem" Error when debug mode,but release has no problem (#66)





 
@dansirming
 One easy thing that's worth trying : edit settings in Mayo (menu Tools-&gt;Options) and restore default values for the "Import/STEP" section

**Comment by HuguesDelorme** [comment] 2021-05-28 08:12
I've provided in `develop` branch a related fix(commit 5f71dd6)
Let me know if it fixes your problem.
Make sure, after compilation, to reset `Import/STEP` options to default values on first run(Tools->Options)

**Comment by dansirming** [comment] 2021-06-06 09:32
today， I tried，the last question has fixed! thank you very much!&nbsp; but when I use&nbsp;opencascade-7.5.0 to bulid mayo,
some link errors as follows：




I has added all libraries which that&nbsp; are located&nbsp; “opencascade-7.5.0\win64\vc14\lib”&nbsp; &nbsp;to mayo project，but all the same!&nbsp; I remove the code&nbsp; of "if OCC_VERSION_HEX &gt;= OCC_VERSION_CHECK(7, 4, 0)" in "io_occ.cpp", the question&nbsp;&nbsp;disappear and never show up， can you help me to fix the question? thank you very much!!!


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fougue/mayo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月28日(星期五) 下午4:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fougue/mayo] "File transfer problem" Error when debug mode,but release has no problem (#66)





 
I've provided in develop branch a related fix(commit 5f71dd6)
 Let me know if it fixes your problem.
 Make sure, after compilation, to reset Import/STEP options to default values on first run(Tools-&gt;Options)

**Comment by HuguesDelorme** [comment] 2021-06-06 10:36
@dansirming 
I can't see the link errors in your last comment.

**Comment by dansirming** [comment] 2021-06-07 01:59
the link errors show in the pictures, can you help me ? thanks!
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fougue/mayo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月6日(星期天) 晚上6:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fougue/mayo] "File transfer problem" Error when debug mode,but release has no problem (#66)





 
@dansirming
 I can't see the link errors in your last comment.

**Comment by HuguesDelorme** [comment] 2021-06-07 06:49
@dansirming
Link errors in the pictures ? But where are those pictures ?

**Comment by dansirming** [comment] 2021-06-07 07:05
pictures that&nbsp;in the&nbsp;Email attachment！but I don't know why you can't see them! now I past link errrors as follow:




: 无法解析的外部符号 "public: __cdecl Mayo::IO::OccGltfReader::OccGltfReader(void)" (??0OccGltfReader@IO@Mayo@@QEAA@XZ)，该符号在函数 "class std::unique_ptr<class Mayo::IO::OccGltfReader,struct std::default_delete<class Mayo::IO::OccGltfReader&gt; &gt; __cdecl std::make_unique<class Mayo::IO::OccGltfReader,0&gt;(void)" (??$make_unique@VOccGltfReader@IO@Mayo@@$$V$0A@@std@@YA?AV?$unique_ptr@VOccGltfReader@IO@Mayo@@U?$default_delete@VOccGltfReader@IO@Mayo@@@std@@@0@XZ) 中被引用
1&gt;io_occ.obj : error LNK2019: 无法解析的外部符号 "public: static class std::unique_ptr<class Mayo::PropertyGroup,struct std::default_delete<class Mayo::PropertyGroup&gt; &gt; __cdecl Mayo::IO::OccGltfReader::createProperties(class Mayo::PropertyGroup *)" (?createProperties@OccGltfReader@IO@Mayo@@SA?AV?$unique_ptr@VPropertyGroup@Mayo@@U?$default_delete@VPropertyGroup@Mayo@@@std@@@std@@***@***.***@@Z)，该符号在函数 "public: virtual class std::unique_ptr<class Mayo::PropertyGroup,struct std::default_delete<class Mayo::PropertyGroup&gt; &gt; __cdecl Mayo::IO::OccFactoryReader::createProperties(struct Mayo::IO::Format const &amp;,class Mayo::PropertyGroup *)const " (?createProperties@OccFactoryReader@IO@Mayo@@UEBA?AV?$unique_ptr@VPropertyGroup@Mayo@@U?$default_delete@VPropertyGroup@Mayo@@@std@@@std@@***@***.***@***@***.***@@Z) 中被引用
1&gt;io_occ.obj : error LNK2019: 无法解析的外部符号 "public: __cdecl Mayo::IO::OccObjReader::OccObjReader(void)" (??0OccObjReader@IO@Mayo@@QEAA@XZ)，该符号在函数 "class std::unique_ptr<class Mayo::IO::OccObjReader,struct std::default_delete<class Mayo::IO::OccObjReader&gt; &gt; __cdecl std::make_unique<class Mayo::IO::OccObjReader,0&gt;(void)" (??$make_unique@VOccObjReader@IO@Mayo@@$$V$0A@@std@@YA?AV?$unique_ptr@VOccObjReader@IO@Mayo@@U?$default_delete@VOccObjReader@IO@Mayo@@@std@@@0@XZ) 中被引用
1&gt;io_occ.obj : error LNK2019: 无法解析的外部符号 "public: static class std::unique_ptr<class Mayo::PropertyGroup,struct std::default_delete<class Mayo::PropertyGroup&gt; &gt; __cdecl Mayo::IO::OccObjReader::createProperties(class Mayo::PropertyGroup *)" (?createProperties@OccObjReader@IO@Mayo@@SA?AV?$unique_ptr@VPropertyGroup@Mayo@@U?$default_delete@VPropertyGroup@Mayo@@@std@@@std@@***@***.***@@Z)，该符号在函数 "public: virtual class std::unique_ptr<class Mayo::PropertyGroup,struct std::default_delete<class Mayo::PropertyGroup&gt; &gt; __cdecl Mayo::IO::OccFactoryReader::createProperties(struct Mayo::IO::Format const &amp;,class Mayo::PropertyGroup *)const " (?createProperties@OccFactoryReader@IO@Mayo@@UEBA?AV?$unique_ptr@VPropertyGroup@Mayo@@U?$default_delete@VPropertyGroup@Mayo@@@std@@@std@@***@***.***@***@***.***@@Z) 中被引用
1&gt;io_occ.obj : error LNK2001: 无法解析的外部符号 "public: virtual bool __cdecl Mayo::IO::OccGltfWriter::transfer(class gsl::span<class Mayo::ApplicationItem const ,-1&gt;,class Mayo::TaskProgress *)" (?transfer@OccGltfWriter@IO@Mayo@@UEAA_NV?$span@$$CBVApplicationItem@Mayo@@***@***.***@@***@***.***@@Z)
1&gt;io_occ.obj : error LNK2001: 无法解析的外部符号 "public: virtual bool __cdecl Mayo::IO::OccGltfWriter::writeFile(class std::filesystem::path const &amp;,class Mayo::TaskProgress *)" (?writeFile@OccGltfWriter@IO@Mayo@@***@***.***@std@@***@***.***@@Z)
1&gt;io_occ.obj : error LNK2001: 无法解析的外部符号 "public: virtual void __cdecl Mayo::IO::OccGltfWriter::applyProperties(class Mayo::PropertyGroup const *)" (?applyProperties@OccGltfWriter@IO@Mayo@@***@***.***@@Z)



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fougue/mayo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月7日(星期一) 下午2:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fougue/mayo] "File transfer problem" Error when debug mode,but release has no problem (#66)





 
@dansirming
 Link errors in the pictures ? But where are those pictures ?

**Comment by HuguesDelorme** [comment] 2021-06-08 15:47
Make sure your git working copy is clean(no pending change) and try to rebuild again ?
The Windows/MSVC appveyor CI is fine so you shouldn't have any problem with building Mayo develop branch

**Comment by dansirming** [comment] 2021-06-12 10:01
I have clean many times,but the link error all the same! what is "The Windows/MSVC appveyor CI"? I&nbsp;I've&nbsp;never&nbsp;heard&nbsp;of it， can you help me to install it , thank you very much!&nbsp; &nbsp;the link error that is in the "io_occ.cpp" ,&nbsp; it seem that&nbsp; can not find the libraries&nbsp;
about&nbsp;OccObjReader or about&nbsp;&nbsp;OccGltfReader


std::unique_ptr<Reader&gt; OccFactoryReader::create(const Format&amp; format) const
{
&nbsp; &nbsp; if (format == Format_STEP)
&nbsp; &nbsp; &nbsp; &nbsp; return std::make_unique<OccStepReader&gt;();
&nbsp; &nbsp; if (format == Format_IGES)
&nbsp; &nbsp; &nbsp; &nbsp; return std::make_unique<OccIgesReader&gt;();
&nbsp; &nbsp; if (format == Format_OCCBREP)
&nbsp; &nbsp; &nbsp; &nbsp; return std::make_unique<OccBRepReader&gt;();
&nbsp; &nbsp; if (format == Format_STL)
&nbsp; &nbsp; &nbsp; &nbsp; return std::make_unique<OccStlReader&gt;();


// the&nbsp; following code will&nbsp;produce some link erros
#if OCC_VERSION_HEX &gt;= OCC_VERSION_CHECK(7, 4, 0)
&nbsp; &nbsp; if (format == Format_GLTF)
&nbsp; &nbsp; &nbsp; &nbsp; return std::make_unique<OccGltfReader&gt;();
&nbsp; &nbsp; if (format == Format_OBJ)
&nbsp; &nbsp; &nbsp; &nbsp; return std::make_unique<OccObjReader&gt;();
#endif


&nbsp; &nbsp; return {};
}&nbsp;




PtrPropertyGroup OccFactoryReader::createProperties(const Format&amp; format, PropertyGroup* parentGroup) const
{
&nbsp; &nbsp; if (format == Format_STEP)
&nbsp; &nbsp; &nbsp; &nbsp; return OccStepReader::createProperties(parentGroup);
&nbsp; &nbsp; if (format == Format_IGES)
&nbsp; &nbsp; &nbsp; &nbsp; return OccIgesReader::createProperties(parentGroup);


// the&nbsp; following code will&nbsp;produce some link erros
#if OCC_VERSION_HEX &gt;= OCC_VERSION_CHECK(7, 4, 0)
&nbsp; &nbsp; if (format == Format_GLTF)
&nbsp; &nbsp; &nbsp; &nbsp; return OccGltfReader::createProperties(parentGroup);
&nbsp; &nbsp; if (format == Format_OBJ)
&nbsp; &nbsp; &nbsp; &nbsp; return OccObjReader::createProperties(parentGroup);
#endif


&nbsp; &nbsp; return {};
}





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fougue/mayo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月8日(星期二) 晚上11:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fougue/mayo] "File transfer problem" Error when debug mode,but release has no problem (#66)





 
Make sure your git working copy is clean(no pending change) and try to rebuild again ?
 The Windows/MSVC appveyor CI is fine so you shouldn't have any problem with building Mayo develop branch

**Comment by HuguesDelorme** [comment] 2021-06-12 14:25
Hello @dansirming 

Sorry for those build problems, though I'm not 100% sure they're caused by me!
What I would like to be sure of is that you don't have any pending change on the Mayo source files that would provoke build errors. Again your git working copy should be "in sync" with the remote `develop` branch.

The Windows/MSVC appveyor CI is the Continuous Integration provided by appveyor for Mayo : each time some changes are pushed to `develop` branch then it triggers a remote build in appveyor(see [last one](https://ci.appveyor.com/project/HuguesDelorme/mayo/builds/39463542))
It's kind of automatic builds, I've configured a "release" build for OpenCascade 7.4.0 and 7.5.0

If the problem still persists then I can propose you to have a phone call next monday through eg Skype so you can screen share the issue.

**Comment by dansirming** [comment] 2021-06-14 09:10
today， I have found&nbsp; a new problem!&nbsp; when I imported some steps into mayo ,but it is not in the center of view, it is&nbsp;situated in the left top corner.&nbsp;it is not&nbsp;perfect! it is difficult to use。the test step file in the&nbsp;&nbsp;mail&nbsp;attachments。can you help me ?





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fougue/mayo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月12日(星期六) 晚上10:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fougue/mayo] "File transfer problem" Error when debug mode,but release has no problem (#66)





 
Hello @dansirming
 
Sorry for those build problems, though I'm not 100% sure they're caused by me!
 What I would like to be sure of is that you don't have any pending change on the Mayo source files that would provoke build errors. Again your git working copy should be "in sync" with the remote develop branch.
 
The Windows/MSVC appveyor CI is the Continuous Integration provided by appveyor for Mayo : each time some changes are pushed to develop branch then it triggers a remote build in appveyor(see last one)
 It's kind of automatic builds, I've configured a "release" build for OpenCascade 7.4.0 and 7.5.0
 
If the problem still persists then I can propose you to have a phone call next monday through eg Skype so you can screen share the issue.

**Comment by HuguesDelorme** [comment] 2021-06-14 21:13
This is an unrelated problem, please create another issue for that and please provide the STEP file

**Comment by dansirming** [comment] 2021-06-19 05:36
ok， thanks！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fougue/mayo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月15日(星期二) 凌晨5:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fougue/mayo] "File transfer problem" Error when debug mode,but release has no problem (#66)





 
This is an unrelated problem, please create another issue for that and please provide the STEP file

**Closed** 2022-03-22 11:04 UTC
